# Generated by Django 3.2 on 2022-12-10 08:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(default='User')),
                ('surname', models.TextField(default='Karaaslan')),
                ('age', models.IntegerField(default=0)),
                ('password', models.TextField()),
            ],
        ),
    ]
