# Generated by Django 3.2 on 2022-12-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_app', '0004_alter_appuser_user_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenthelp',
            name='equipment_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
