# Generated by Django 4.1.4 on 2022-12-24 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_app', '0005_equipmenthelp_equipment_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='appuser',
            name='avatar_id',
            field=models.PositiveIntegerField(default=1, validators=[
                                              django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='equipmenthelp',
            name='equipment_photo',
            field=models.ImageField(blank=True, upload_to='equipments'),
        ),
    ]
