# Generated by Django 3.2 on 2022-12-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_app', '0005_equipmenthelp_equipment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profile_photos'),
        ),
        migrations.AlterField(
            model_name='equipmenthelp',
            name='equipment_photo',
            field=models.ImageField(blank=True, upload_to='equipments'),
        ),
    ]
