# Generated by Django 3.2 on 2022-12-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_app', '0006_auto_20221224_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenthelp',
            name='phone_number',
            field=models.CharField(default='+905555555555', max_length=13),
        ),
    ]
