# Generated by Django 3.2 on 2022-12-24 22:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_app', '0008_remove_appuser_profile_photo_appuser_avatar_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('start_latitude', models.CharField(max_length=10)),
                ('start_longitude', models.CharField(max_length=10)),
                ('finish_latitude', models.CharField(max_length=10)),
                ('finish_longitude', models.CharField(max_length=10)),
                ('comment', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('companion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='companion', to='bridge_app.appuser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator', to='bridge_app.appuser')),
            ],
        ),
    ]
