# Generated by Django 3.2 on 2022-12-25 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_app', '0012_auto_20221225_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companionrequest',
            name='finish_road',
        ),
        migrations.RemoveField(
            model_name='companionrequest',
            name='finish_subrub',
        ),
        migrations.RemoveField(
            model_name='companionrequest',
            name='finish_town',
        ),
        migrations.RemoveField(
            model_name='companionrequest',
            name='start_road',
        ),
        migrations.RemoveField(
            model_name='companionrequest',
            name='start_subrub',
        ),
        migrations.RemoveField(
            model_name='companionrequest',
            name='start_town',
        ),
    ]
