# Generated by Django 3.2 on 2022-12-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_app', '0013_auto_20221225_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='companionrequest',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
